### ISSUE TITLE
acmetool doesn't work at OpenBSD 5.7 i386

### ISSUE THREAD

**Issue by ligurio** [hlandau/acme#20]
acmetool v0.0.12

$ sudo acmetool quickstart
Illegal instruction (core dumped) 
$ sudo gdb -c acmetool.core bin/acmetool 
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-unknown-openbsd5.7"...
Core was generated by `acmetool'.
Program terminated with signal 4, Illegal instruction.
Die: DW_TAG_unspecified_type (abbrev = 10, offset = 939302)
        has children: FALSE
        attributes:
                DW_AT_name (DW_FORM_string) string: "<unspecified>"
Dwarf Error: Cannot find type of die [in module /home/estet/acmetool-v0.0.12-openbsd_386/bin/acmetool]
(gdb) $

**Comment by hlandau** [comment]
The openbsd build is cross-compiled by travis, it doesn't get tested. I'll make an openbsd VM and test.

**Comment by hlandau** [comment]
I'm unable to reproduce this with the v0.0.12 `openbsd_i386` build on OpenBSD 5.8 i386.

Maybe this is an issue with instruction set extensions available on your processor?

**Comment by ligurio** [comment]
> Maybe this is an issue with instruction set extensions available on your processor? Random guess.

Probably. My CPU mode and flags:
cpu0: Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class) 499 MHz
cpu0: FPU,DE,PSE,TSC,MSR,CX8,SEP,PGE,CMOV,CFLUSH,MMX,MMXX,3DNOW2,3DNOW
cpu0 at mainbus0: (uniprocessor)

**Comment by hlandau** [comment]
So, try building yourself and see if this happens?

**Comment by hlandau** [comment]
This looks to be relevant: https://groups.google.com/forum/?_escaped_fragment_=topic/golang-nuts/NsROxh3Dc6M#!topic/golang-nuts/NsROxh3Dc6M
Probably a lack of SSE2 is the issue. It looks like you can set Go to use the x87 FPU rather than SSE2 by compiling with env GO386=387.

Maybe I should set the 386 builds to have GO386=387, most people will presumably use the amd64 builds so this isn't a big loss. It's not like acmetool is performance sensitive.

**Comment by hlandau** [comment]
Releases from v0.0.16 onwards use the x87 FPU for x86 builds.

**Comment by ligurio** [comment]
acmetool v0.0.16 builded for OpenBSD i386 platform works for me. Many thanks for help!
