### ISSUE TITLE
acmetool 0.0.58 doesn't build with go 1.7.5

### ISSUE THREAD

**Issue by Thermi** [hlandau/acme#239]
acmetool 0.0.58 doesn't build with go 1.7.5:

```
/usr/lib/go/pkg/tool/linux_amd64/link -o $WORK/github.com/hlandau/acme/cmd/acmetool/_obj/exe/a.out -L $WORK -L /home/thermi/aur/AUR4/acmetool/src/pkg/linux_amd64 -extld=gcc -buildmode=exe -buildid=d4294c23e4a9b9baf2977e06cddf729632c9225f $WORK/github.com/hlandau/acme/cmd/acmetool.a
mkdir -p /home/thermi/aur/AUR4/acmetool/src/bin/
cp $WORK/github.com/hlandau/acme/cmd/acmetool/_obj/exe/a.out /home/thermi/aur/AUR4/acmetool/src/bin/acmetool
_/home/thermi/aur/AUR4/acmetool/src/acme-0.0.58/cmd/acmetool
# _/home/thermi/aur/AUR4/acmetool/src/acme-0.0.58/cmd/acmetool
./main.go:387: too many arguments in call to hooks.NotifyLiveUpdated
```

**Comment by hlandau** [comment]
Fixed for v0.0.59.
